import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>{`
        h2 {
          font-size: 40px;
        }
        h3 {
          font-size: 25px;
        }
      `}</style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainNav}>
        <ul>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/about">
            <li>About</li>
          </Link>
          <Link href="/blog">
            <li>Blog</li>
          </Link>
          <Link href="/contact">
            <li>Contact Us</li>
          </Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Hunting Coder</h1>
        <div className={styles.imgWrap}>
          <Image
            className={styles.myImg}
            src="/coder.avif"
            alt=""
            width={300}
            height={200}
          />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="blog">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
